-- Alert Log Table for Monitoring Dashboard
-- Stores all alerts generated by the monitoring system
-- Week 4 Day 3-4: Alerting Configuration

CREATE TABLE IF NOT EXISTS alerts_log (
    id SERIAL PRIMARY KEY,
    alert_type VARCHAR(50) NOT NULL,           -- 'api_error_rate', 'latency_spike', 'model_degradation', 'data_drift'
    severity VARCHAR(20) NOT NULL,              -- 'info', 'warning', 'critical'
    title VARCHAR(200) NOT NULL,
    message TEXT,
    details JSONB,                              -- Additional alert details (metric values, etc.)
    email_sent BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Index for querying recent alerts
CREATE INDEX IF NOT EXISTS idx_alerts_log_created_at ON alerts_log(created_at DESC);

-- Index for alert type filtering
CREATE INDEX IF NOT EXISTS idx_alerts_log_type ON alerts_log(alert_type);

-- Index for severity filtering
CREATE INDEX IF NOT EXISTS idx_alerts_log_severity ON alerts_log(severity);

-- View: Active alerts (last 24 hours)
CREATE OR REPLACE VIEW active_alerts AS
SELECT * FROM alerts_log
WHERE created_at > NOW() - INTERVAL '24 hours'
ORDER BY created_at DESC;

-- View: Alert summary by type (last 7 days)
CREATE OR REPLACE VIEW alert_summary AS
SELECT
    alert_type,
    severity,
    COUNT(*) as alert_count,
    MAX(created_at) as last_occurred
FROM alerts_log
WHERE created_at > NOW() - INTERVAL '7 days'
GROUP BY alert_type, severity
ORDER BY alert_type, severity;
